# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('TASK_ASSIGNED', 'Task Assigned'),
                    ('TASK_COMPLETED', 'Task Completed'),
                    ('TASK_COMMENTED', 'Task Commented'),
                    ('TASK_ARCHIVED', 'Task Archived'),
                    ('TASK_OVERDUE', 'Task Overdue'),
                    ('TASK_DEADLINE_APPROACHING', 'Task Deadline Approaching'),
                    ('PROJECT_UPDATED', 'Project Updated'),
                ],
                db_index=True,
                default='PROJECT_UPDATED',
                max_length=50,
            ),
        ),
    ]
