# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_deadline_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('TASK_ASSIGNED', 'Task Assigned'),
                    ('TASK_COMPLETED', 'Task Completed'),
                    ('TASK_COMMENTED', 'Task Commented'),
                    ('TASK_ARCHIVED', 'Task Archived'),
                    ('TASK_OVERDUE', 'Task Overdue'),
                    ('TASK_DEADLINE_APPROACHING', 'Task Deadline Approaching'),
                    ('PROJECT_UPDATED', 'Project Updated'),
                    ('PROJECT_INVITATION_SENT', 'Project Invitation Sent'),
                    ('PROJECT_INVITATION_ACCEPTED', 'Project Invitation Accepted'),
                    ('PROJECT_INVITATION_DECLINED', 'Project Invitation Declined'),
                    ('PROJECT_INVITATION_REVOKED', 'Project Invitation Revoked'),
                    ('MEMBER_ADDED', 'Member Added'),
                    ('MEMBER_ROLE_UPDATED', 'Member Role Updated'),
                    ('MEMBER_REMOVED', 'Member Removed'),
                ],
                db_index=True,
                default='PROJECT_UPDATED',
                max_length=50,
            ),
        ),
    ]
