# Generated by Codex on 2026-05-21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('CLIENT', 'Client'), ('VIEWER', 'Viewer')], db_index=True, default='DEVELOPER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('token', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['project', 'status'], name='projects_pr_project_1d057c_idx'),
                    models.Index(fields=['invited_user', 'status'], name='projects_pr_invited_85394f_idx'),
                    models.Index(fields=['expires_at', 'status'], name='projects_pr_expires_3c6ddd_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('project', 'invited_user'), name='unique_pending_project_invitation'),
                ],
            },
        ),
    ]
