# Generated by Django 5.2.14 on 2026-05-20 13:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], db_index=True, max_length=50)),
                ('target_type', models.CharField(choices=[('PROJECT', 'Project'), ('TASK', 'Task'), ('AUTH', 'Authentication')], db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='Readable representation of the target at the time of log creation.', max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured changelog, original state, or transition data.')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='idx_target_lookup'), models.Index(fields=['actor', '-created_at'], name='idx_actor_timeline')],
            },
        ),
    ]
