# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskattachment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['is_deleted', 'is_archived', 'status', 'due_date'],
                name='task_deadline_state_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['due_date', 'status'],
                name='task_due_status_idx',
            ),
        ),
    ]
