# Generated by Codex on 2026-05-21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectinvitation'),
        ('tasks', '0005_task_deadline_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=60)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code for the label badge.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g. #ff5733).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_labels', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.tasklabel'),
        ),
        migrations.AddIndex(
            model_name='tasklabel',
            index=models.Index(fields=['project', 'name'], name='label_project_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasklabel',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_label_slug_per_project'),
        ),
    ]
