# Generated by Django 5.2.14 on 2026-05-20 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], db_index=True, max_length=50)),
                ('target_type', models.CharField(choices=[('PROJECT', 'Project'), ('TASK', 'Task'), ('USER', 'User')], db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('target_repr', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='common_acti_target__fbb648_idx'), models.Index(fields=['action_type'], name='common_acti_action__d17ce8_idx'), models.Index(fields=['created_at'], name='common_acti_created_3a96f8_idx')],
            },
        ),
    ]
