# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('CREATED', 'Created'),
                    ('UPDATED', 'Updated'),
                    ('DELETED', 'Deleted'),
                    ('STATUS_CHANGED', 'Status Changed'),
                    ('ASSIGNED', 'Assigned'),
                    ('LOGIN', 'Login'),
                    ('LOGOUT', 'Logout'),
                    ('MEMBER_ADDED', 'Member Added'),
                    ('MEMBER_REMOVED', 'Member Removed'),
                    ('MEMBER_ROLE_UPDATED', 'Member Role Updated'),
                    ('LABEL_ASSIGNED', 'Label Assigned'),
                    ('LABEL_REMOVED', 'Label Removed'),
                    ('INVITATION_SENT', 'Invitation Sent'),
                    ('INVITATION_ACCEPTED', 'Invitation Accepted'),
                    ('INVITATION_DECLINED', 'Invitation Declined'),
                    ('INVITATION_REVOKED', 'Invitation Revoked'),
                    ('INVITATION_EXPIRED', 'Invitation Expired'),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(
                choices=[
                    ('PROJECT', 'Project'),
                    ('TASK', 'Task'),
                    ('USER', 'User'),
                    ('PROJECT_MEMBER', 'Project Member'),
                    ('PROJECT_INVITATION', 'Project Invitation'),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
